name: FocusDesk
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  google_fonts: ^6.3.3
  intl: ^0.20.2
  provider: ^6.1.5+1
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  wakelock_plus: ^1.4.0
  battery_plus: ^7.0.0


  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/bg1.jpg
    - assets/bg2.jpg
    - assets/bg3.jpg
    - assets/bg4.jpg
    - assets/bg5.jpg


